version: '3.1'

services:
  db:
      image: postgres
      restart: always
      networks:
        - backend
      volumes:
        - /webapps/share:/share
        - db-data:/var/lib/postgresql/data
      ports:
        - 5432:5432


volumes:
  db-data:

networks:
  backend:


